name: .NET Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        test-type: [unit-tests, integration-tests]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            8.0.x

      - name: Run tests
        uses: ./.github/actions/test-dotnet
        with:
          type: ${{ matrix.test-type }}
          project-id: ${{ secrets.PROJECT_ID }}
