name: .NET Build & Test

on:
  push:
    branches: [ develop ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest]
        os: [windows-latest]
        dotnet-version: [8.0.x]
        test-type: [unit-tests, integration-tests]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Run tests
        uses: ./.github/actions/test-dotnet
        with:
          type: ${{ matrix.test-type }}
          project-id: ${{ secrets.PROJECT_ID }}
          dotnet-version: ${{ matrix.dotnet-version }}