name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
  pull_request:

jobs:
  nuget:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            8.0.x

      - name: Build Release
        run: dotnet build Reown.NoUnity.slnf -c Release --restore

      - name: Pack nugets
        run: dotnet pack Reown.NoUnity.slnf -c Release --no-build --output .
        
      - name: List files
        run: tree -L 3

#      - name: Push to NuGet
#        run: dotnet nuget push "*.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            **/bin/**/*.dll
            !**/Tests/**/bin/**/*.dll